version: '3.4'

services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./volumes/data:/var/opt/mssql/data 
      - ./volumes/log:/var/opt/mssql/log 
      - ./volumes/secrets:/var/opt/mssql/secrets 
    ports:
      - "1433:1433"